# Generated by Django 5.2.5 on 2025-10-21 21:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='calories_burned',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='name',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('Running', 'Running'), ('Cycling', 'Cycling'), ('Swimming', 'Swimming'), ('Walking', 'Walking'), ('Gym', 'Gym'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='activity',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.DurationField(help_text='Activity duration'),
        ),
    ]
