# Generated by Django 5.2.7 on 2025-10-23 17:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0002_remove_activity_calories_burned_remove_activity_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='calories_burned',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='activity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
