# Generated by Django 5.2.7 on 2025-10-28 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0003_activity_calories_burned_activity_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-date', '-created_at']},
        ),
    ]
