# Generated by Django 5.2.7 on 2025-10-28 07:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0004_alter_activity_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
